# Generated by Django 4.2.5 on 2023-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=20, verbose_name="이름"),
                ),
                (
                    "user_id",
                    models.CharField(
                        default="", max_length=20, unique=True, verbose_name="아이디"
                    ),
                ),
                ("age", models.CharField(default="", max_length=20, verbose_name="나이")),
                (
                    "phone",
                    models.CharField(default="", max_length=11, verbose_name="번호"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "accounts",
                "db_table": "UserAccounts",
            },
        ),
    ]
