# Generated by Django 4.2.5 on 2023-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food", "0001_initial"),
        ("accounts", "0001_initial"),
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="user_dinner",
            field=models.ManyToManyField(related_name="dinner_account", to="food.food"),
        ),
        migrations.AddField(
            model_name="account",
            name="user_exercise_c",
            field=models.ManyToManyField(
                related_name="exercise_c_account", to="exercise.exercise_cardio"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_exercise_l",
            field=models.ManyToManyField(
                related_name="exercise_l_account", to="exercise.exercise_low"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_exercise_u",
            field=models.ManyToManyField(
                related_name="exercise_u_account", to="exercise.exercise_upper"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_lunch",
            field=models.ManyToManyField(related_name="lunch_account", to="food.food"),
        ),
        migrations.AddField(
            model_name="account",
            name="user_morning",
            field=models.ManyToManyField(
                related_name="morning_account", to="food.food"
            ),
        ),
    ]
