# Generated by Django 4.2.5 on 2023-11-30 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.CharField(max_length=10, verbose_name="시작체중")),
                ("tall", models.CharField(max_length=3, verbose_name="키")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MEN", "남자"), ("WOMEN", "여자")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "now_weight",
                    models.CharField(max_length=10, null=True, verbose_name="현재체중"),
                ),
                ("fat", models.CharField(max_length=20, verbose_name="체지방량")),
                ("muscle", models.CharField(max_length=20, verbose_name="골격근량")),
                ("target_weight", models.CharField(max_length=20, verbose_name="목표체중")),
                ("datepicker1", models.CharField(max_length=10, verbose_name="시작날짜")),
                ("datepicker2", models.CharField(max_length=10, verbose_name="종료날짜")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "setting",
                "db_table": "UserSetting",
            },
        ),
    ]
