# Generated by Django 4.2.5 on 2023-11-30 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=100, verbose_name="음식 이름")),
                ("food_calorie", models.CharField(max_length=5, verbose_name="음식 칼로리")),
            ],
            options={
                "verbose_name": "food",
                "db_table": "UserFood",
            },
        ),
        migrations.CreateModel(
            name="Food_morning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="아침에 먹은 음식")),
                ("calorie", models.CharField(max_length=5, verbose_name="아침에 먹은 칼로리")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "morning_food",
                "db_table": "Morning_Food",
            },
        ),
        migrations.CreateModel(
            name="Food_lunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="점심에 먹은 음식")),
                ("calorie", models.CharField(max_length=5, verbose_name="점심에 먹은 칼로리")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "lunch_food",
                "db_table": "Lunch_Food",
            },
        ),
        migrations.CreateModel(
            name="Food_dinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="저녁에 먹은 음식")),
                ("calorie", models.CharField(max_length=5, verbose_name="저녁에 먹은 칼로리")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "dinner_food",
                "db_table": "Dinner_Food",
            },
        ),
        migrations.CreateModel(
            name="Calorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "health_calorie",
                    models.CharField(max_length=5, verbose_name="소비한 칼로리"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "calorie",
                "db_table": "UserCalorie",
            },
        ),
    ]
